@Library('ceiba-jenkins-library') _
pipeline {
  //Donde se va a ejecutar el Pipeline
  agent {
    label 'Slave_Induccion'
  }

  //Opciones específicas de Pipeline dentro del Pipeline
  options {
    	buildDiscarder(logRotator(numToKeepStr: '3'))
 		disableConcurrentBuilds()
  }

  //Una sección que define las herramientas “preinstaladas” en Jenkins
  tools {
    jdk 'JDK11_Centos' //Versión preinstalada en la Configuración del Master - Modificar según versión de JDK utilizada
    nodejs 'NodeJS15'
  }

  //Aquí comienzan los “ítems” del Pipeline
  stages{
    stage('Checkout') {
      steps{
        echo "------------>Checkout<------------"
        checkout scm
      }
    }

    stage('Compile & Unit Tests') {
      steps{
        echo "------------>Compile & Unit Tests<------------"
        sh 'chmod +x ./Clinica/gradlew'
        sh './Clinica/gradlew --b ./Clinica/build.gradle clean'
        sh './Clinica/gradlew --b ./Clinica/build.gradle test'
        junit '**/build/test-results/test/*.xml'

      }
    }

    stage('Static Code Analysis') {
      steps{
        echo '------------>Análisis de código estático<------------'
        sonarqubeMasQualityGatesP(sonarKey:'co.com.ceiba.adn:clinicaodontologicaback-lorena.sanchez',
                sonarName:'ADN-ClinicaOdontologicaBack[lorena.sanchez]',
                sonarPathProperties:'./sonar-project.properties')
            }
      }


    stage('Build') {
      steps {
        echo "------------>Build<------------"
        sh './Clinica/gradlew --b ./Clinica/build.gradle build -x test'
      }
    }
	}

  post {
    always {
      echo 'This will always run'
    }
    success {
      echo 'This will run only if successful'
    }
    failure {
      echo 'This will run only if failed'
      mail (to: 'lorena.sanchez@ceiba.com.co',subject: "Failed Pipeline:${currentBuild.fullDisplayName}",body: "Something is wrong with ${env.BUILD_URL}")
    }
    unstable {
      echo 'This will run only if the run was marked as unstable'
    }
    changed {
      echo 'This will run only if the state of the Pipeline has changed'
      echo 'For example, if the Pipeline was previously failing but is now successful'
    }
  }
}
